//DOCUMENT OJBJECT MODEL IN JAVASCRIPT

//WHAT IS DOM

//ITS BASICALLY A PROGRAMMING INTERFACe FOR WEB PAGES/HTML ELEMENTS
//STRICTURE THAT WE CAN INTERACT VIA JAVASCRIPT
//INCLUDES TAGS,ATTRIBUTES,TEXT NODES.ETC
//REPRESENTED AS  A TREE STRUCTURE
console.dir(window.document);

console.log(document.body.innerHTML);

//document.body.innerHTML = `<h1>HELLO WELCOME TO THE DOM MASTERCLASS</h1>`;

//document.write("lets start lesson 1 ");

//THERE ARE DIFFERENT METHODS IN GETTING THE ELEMENTS IN THE HTML

//THE FIRST ONE IS  getElementById

const abc = document.getElementById(`main`);
//main.innerHTML = `<h1>HELLO WELCOME TO THE DOM MASTERCLASS</h1>`;
